### ISSUE TITLE
Zenity output confuses gpg

### ISSUE THREAD

**Issue by DemiMarie** [HW42/qubes-app-linux-split-gpg2#14]
On my message, zenity displays an assertion failure error message, which somehow gets sent to GPG and interpreted as an invalid IPC command.

**Comment by HW42** [comment]
My zenity does also print some GTK assertion failue. But is seems to go stderr as expected. Can you provide logs and or steps to reproduce?

**Comment by DemiMarie** [comment]
> My zenity does also print some GTK assertion failue. But is seems to go stderr as expected. Can you provide logs and or steps to reproduce?

It was a buggy systemd unit on my end.  I forgot `StandardError=journal`, so stderr got mixed in with stdout.
